version: '3'
services:
  web:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql
  redis:
    image: redis:latest
    expose:
      - 6379

volumes:
  mysql:
  mysql_config: