name: ci

on:
  push:
    branches:
      - "deployment"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      -
        name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        run: |
          docker-compose up --build -d

          WEB_IMAGE_NAME=$(docker-compose images | grep "web" | awk '{print $2}')
          echo "Web image name: $WEB_IMAGE_NAME"

          docker tag $WEB_IMAGE_NAME ${{ secrets.DOCKERHUB_USERNAME }}/digitalhospital:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/digitalhospital:latest

